export const metadata = {
  title: 'uramtorul.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}
        <h1>footer</h1>
      </body>
      
    </html>
  )
}
