export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function MarketingLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div><h1>Header</h1></div>
        {children}
        <div><h1>Footer</h1></div>
        </body>
    </html>
  )
}
